 ##continuumio/anaconda3
FROM  nvcr.io/nvidia/rapidsai/rapidsai-core:23.04-cuda11.8-runtime-ubuntu22.04-py3.10
RUN  apt-get -y update
RUN  apt-get -y install graphviz
#RUN git clone https://github.com/DeepRegNet/DeepReg.git
##RUN cp -r  DeepReg /rapids/notebooks/
# clone DeepReg
RUN git clone https://github.com/DeepRegNet/DeepReg.git
WORKDIR DeepReg
RUN git pull

# install conda env
RUN conda env create -f environment.yml \
    && conda init bash \
    && echo "conda activate deepreg" >> /root/.bashrc
#RUN conda env create -f /DeepReg/environment.yml
