

 ##continuumio/anaconda3
FROM  nvcr.io/nvidia/rapidsai/rapidsai-core:23.04-cuda11.8-runtime-ubuntu20.04-py3.10
RUN  apt-get -y update
RUN  apt-get -y install graphviz
ENV CONDA_DIR=/opt/conda
## clone DeepReg
RUN git clone https://github.com/DeepRegNet/DeepReg.git
WORKDIR DeepReg
RUN git pull
#### install conda env
RUN conda env create -f environment.yml \
    && conda init bash \
    && echo "conda activate deepreg" >> /root/.bashrc
### install deepreg
ENV CONDA_PIP="${CONDA_DIR}/envs/deepreg/bin/pip"
RUN ${CONDA_PIP} install -e .
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN /opt/conda/envs/deepreg/bin/pip install opencv-python
RUN mkdir /DEEPREG
###ADD DeepRegForSNIPR /DEEPREG/

RUN mkdir /templateventricle
RUN mkdir /templatenifti
RUN mkdir /templatemasks
COPY scct_strippedResampled1.nii.gz   /templatenifti/
COPY  midlinecssfResampled1.nii.gz   /templatemasks/
COPY scct_strippedResampled1_onlyventricle.nii.gz /templateventricle/
RUN mkdir -p /callfromgithub
RUN chmod 755 /callfromgithub
COPY downloadcodefromgithub.sh /callfromgithub/
RUN chmod +x /callfromgithub/downloadcodefromgithub.sh
RUN apt install -y \
  dcm2niix  \ 
  vim  \ 
  zip  \ 
  unzip  \ 
  curl  \ 
  git \
  tree
RUN /opt/conda/envs/deepreg/bin/pip install \
  nibabel  \ 
  numpy  \ 
  xmltodict  \ 
  pandas  \ 
  requests  \ 
  pydicom  \ 
  python-gdcm  \ 
  glob2  \ 
  scipy  \ 
  pypng  \
  PyGithub \
  SimpleITK \
  h5py \
  webcolors \
  scikit-image
ENV REDCAP_API='36F3BA05DE0507BEBDFB94CC5DA13F93'